"""have_seat_id_unique

Revision ID: 9483dcee9f6b
Revises: 97a37a42d702
Create Date: 2025-08-04 15:34:30.822923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9483dcee9f6b'
down_revision: Union[str, Sequence[str], None] = '97a37a42d702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'booking_seats', ['seat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking_seats', type_='unique')
    # ### end Alembic commands ###
