"""add_relationships

Revision ID: bb30b29fee14
Revises: 66d2a08d906d
Create Date: 2025-08-02 01:01:19.292736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb30b29fee14'
down_revision: Union[str, Sequence[str], None] = '66d2a08d906d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('showtime_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bookings', 'showtimes', ['showtime_id'], ['id'])
    op.add_column('seats', sa.Column('showtime_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'seats', 'showtimes', ['showtime_id'], ['id'])
    op.add_column('showtimes', sa.Column('movie_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'showtimes', 'movies', ['movie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'showtimes', type_='foreignkey')
    op.drop_column('showtimes', 'movie_id')
    op.drop_constraint(None, 'seats', type_='foreignkey')
    op.drop_column('seats', 'showtime_id')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'showtime_id')
    # ### end Alembic commands ###
